server:
  port: 1111
spring:
    application:
     name: STOCK-PRICE-SERVICE
    datasource:
     driver-class-name: org.h2.Driver
     password: null
     url: jdbc:h2:mem:testdb
     username:  sa