insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE)VALUES(101,'TCS',900.00);
insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE)VALUES(102,'BHEL',40.00);
insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE)VALUES(103,'INFOSYS',950.00);
insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE)VALUES(104,'HCL',700.00);